### ISSUE TITLE
extends SlashCommandBuilder

### ISSUE THREAD

**Issue by HarukaYamamoto0** [whoisniskii/Suki-Rewrite#1]
https://github.com/whoisniskii/Suki-Rewrite/blob/1796428f5fe48ce19efb128a8429925db393f071/src/classes/Command.ts#L8

você poderia extender a class command para poder pegar os métodos da class SlashCommandBuilder do discord.js assim você pode usar os métodos dele, sem ter que criar um objeto data na  mão, eu faço isso nos meus bots, e isso facilita muito.

**Comment by whoisniskii** [comment]
Não faz sentido eu baixar o @discordjs/builders só pra estender uma única classe
